import os

from dotenv import load_dotenv


load_dotenv()


DEEPSEEK_API_KEY = os.environ.get("DEEPSEEK_API_KEY")

if not DEEPSEEK_API_KEY:
    raise RuntimeError("DEEPSEEK_API_KEY is not set")


DEEPSEEK_BASE_URL = "https://api.deepseek.com"
DEEPSEEK_MODEL = "deepseek-v4-flash"

DEEPSEEK_TIMEOUT_SECONDS = 30.0
DEEPSEEK_MAX_RETRIES = 0

LLM_APP_MAX_RETRIES = 1
LLM_RETRY_DELAY_SECONDS = 0.5

RATE_LIMIT_REQUESTS = 10
RATE_LIMIT_WINDOW_SECONDS = 60

MAX_MESSAGE_CHARACTERS = 4000
MAX_CONVERSATION_MESSAGES = 20
MAX_CONVERSATION_CHARACTERS = 20000